### PR TITLE
Adding Polygon support

### PR DESCRIPTION
**Pull request by Jonas-Lieske**
Here is my solution on how to implement Polygon support as discussed in #21.

**Requirements**
The hardhat-etherscan package needs to be updated to version 3.0.0 since it offers a new feature to configure multiple API keys for scans at once. The doc entry is [HERE](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html#multiple-api-keys-and-alternative-block-explorers). I haven't noticed any problems with the update.

**Improvements that could be made**
I do not have any experience with REACT so I didn't try to change anything on the code base. It still says ETH for the pricing and the polygon chain is not being recognized as a main chain.
I also needed to use the gasMultiplier for polygon chain since there have been problems with the deployment and verification, because of a too low gas fee. AFAIK this is a problem with the calculation of gas fee by hardhat.

I tested it and it worked, however I only recently got into the field of smart contracts so I would appreciate any feedback!

### CODE REVIEW

**Comment by liarco** [comment]
Hi @Jonas-Lieske, thank you very much for this contribution, I'm gonna review this PR as soon as possible.

Would you mind if I make some changes (if needed) or implement the missing stuff for the DAPP? And also, would you be willing to test the final result so we can make sure everything is fine before merging?

Thank you.

**Comment by liarco** [comment]
@tab00 we don't agree with the first suggestion provided by OpenSea ("Overriding isApprovedForAll() to reduce trading friction"). The hard-coded approval of the OpenSea marketplace is something that we don't want to implement by default in our contracts since we see it as a bad-practice from a security point of view.

That said, I need to do some research about the rest of the article. 😉

**Comment by tab00** [comment]
> we don't agree with the first suggestion provided by OpenSea ("Overriding isApprovedForAll() to reduce trading friction")

Yes, I had come across some discussion recently about the risks of that in https://gist.github.com/483eb43bc6ed30b14f01e01842e3339b#gistcomment-4073311

**Comment by liarco** [comment]
Hi @Jonas-Lieske it seems like I made a mistake while trying to rebase your fork on the latest version and now I have no access to your repository.

Would you please apply the following patch as a new commit and push it to your branch?
```diff
commit c0da904673c48a72bff04eed6cab38fadff13a85
Author: Marco Lipparini <developer@liarco.net>
Date:   Sat Mar 5 20:35:11 2022 +0100

    Added Polygon support

diff --git a/smart-contract/hardhat.config.ts b/smart-contract/hardhat.config.ts
index 0007696..4b4fe0b 100644
--- a/smart-contract/hardhat.config.ts
+++ b/smart-contract/hardhat.config.ts
@@ -112,6 +112,10 @@ const config: HardhatUserConfig = {
       // Ethereum
       rinkeby: process.env.BLOCK_EXPLORER_API_KEY,
       mainnet: process.env.BLOCK_EXPLORER_API_KEY,
+
+      // Polygon
+      polygon: process.env.BLOCK_EXPLORER_API_KEY,
+      polygonMumbai: process.env.BLOCK_EXPLORER_API_KEY,
     },
   },
 };
diff --git a/smart-contract/lib/Networks.ts b/smart-contract/lib/Networks.ts
index 687a252..d217c12 100644
--- a/smart-contract/lib/Networks.ts
+++ b/smart-contract/lib/Networks.ts
@@ -3,7 +3,7 @@ import NetworkConfigInterface from './NetworkConfigInterface';
 export const ethereumTestnet: NetworkConfigInterface = {
   chainId: 4,
   blockExplorer:{
-    name: 'Etherscan',
+    name: 'Etherscan (Rinkeby)',
     generateContractUrl: (contractAddress: string) => `https://rinkeby.etherscan.io/address/${contractAddress}`,
   },
 }
@@ -15,3 +15,19 @@ export const ethereumMainnet: NetworkConfigInterface = {
     generateContractUrl: (contractAddress: string) => `https://etherscan.io/address/${contractAddress}`,
   },
 }
+
+export const polygonTestnet: NetworkConfigInterface = {
+  chainId: 80001,
+  blockExplorer:{
+    name: 'Polygonscan (Mumbai)',
+    generateContractUrl: (contractAddress: string) => `https://mumbai.polygonscan.com/address/${contractAddress}`,
+  },
+}
+
+export const polygonMainnet: NetworkConfigInterface = {
+  chainId: 137,
+  blockExplorer: {
+    name: 'Polygonscan',
+    generateContractUrl: (contractAddress: string) => `https://polygonscan.com/address/${contractAddress}`,
+  },
+}
```

If you save it to a `polygon.patch` file you should be able to apply it with `git apply polygon.patch`. Then I should be able to re-open this PR.

My changes in version `2.0.0` are based on your original idea and this patch should enable support for Polygon network.
You should then be able to test it by updating the imports in the configuration file:
https://github.com/hashlips-lab/nft-erc721-collection/blob/0c1474c803467ff80c7725beb0b688eb0489d6d4/smart-contract/config/CollectionConfig.ts#L2
And  referencing the Polygon networks here:
https://github.com/hashlips-lab/nft-erc721-collection/blob/0c1474c803467ff80c7725beb0b688eb0489d6d4/smart-contract/config/CollectionConfig.ts#L7-L8

The env variables are now generic so there is no need to add new ones, you can simply use the default ones.

Let me know if you can help me with this, thank you very much! 🙏

**Comment by Jonas-Lieske** [comment]
Hey @liarco, I've applied and pushed the changes you mentioned, ran the tests and also did some manual testing.
The only thing that I noticed is that the currency being displayed on the minting page is still ETH, the rest is working fine 🙂

**Comment by liarco** [comment]
Thank you very much @Jonas-Lieske, I really appreciate it.

You are right I have to make it customizable as well. 😉 I see you also mentioned you had to use the "gasMultiplier for polygon chain", is this still relevant? Would you please elaborate on this so I can understand if we need to take it into consideration too?

**Comment by Jonas-Lieske** [comment]
No problem @liarco, I gotta thank you for this awesome repo 😉

Interestingly enough, the problem I mentioned where the gasMultiplier was needed is not occurring anymore 🤔

When I tested my implementation, an error message told me that the gas fees were set too low to deploy the contract.
I researched about it and found out that the gas fees were miscalculated by hardhat.
To fix this I set the gasMultiplier in the hardhat config to 1.1, meaning it would set them 10% higher than estimated.
I'm glad that this issue is fixed 😁

**Comment by liarco** [comment]
@Jonas-Lieske 🙏

I'm happy to hear this might be fixed. Infura (which is also used by MetaMask) had a lot of issue in the past days so I have seen many people complaining about failing transactions, wrong gas estimations, etc. I hope it was the culprit.

I committed the support for custom token symbols, I also decided to append an explicit ` (test)` suffix (e.g. `ETH (test)`) for testing networks.

Now I think we should take care of the optimizations suggested by OpenSea. I need to understand the purpose of each of them and I would like to limit the changes to what is absolutely required.

**Comment by Juan34-crypto** [comment]
You guys are the best !! I just want to now if the code is ready to use for polygon, or i need to wait for another tutorial to start my smart contract , i been trying everything and I see you guys are so close to get this code ready

**Comment by liarco** [comment]
Hi @Juan34-crypto, it's not ready for production but if you could test it and give us feedback that would be appreciated.

You can clone the git repo from this PR or you can download it as a [ZIP file](https://github.com/Jonas-Lieske/nft-erc721-collection/archive/refs/heads/main.zip).

Then you should be able to follow my instructions from the previous message:
> ...
> My changes in version `2.0.0` are based on your original idea and this patch should enable support for Polygon network. You should then be able to test it by updating the imports in the configuration file:
> 
> https://github.com/hashlips-lab/nft-erc721-collection/blob/0c1474c803467ff80c7725beb0b688eb0489d6d4/smart-contract/config/CollectionConfig.ts#L2
> 
> 
> And referencing the Polygon networks here:
> https://github.com/hashlips-lab/nft-erc721-collection/blob/0c1474c803467ff80c7725beb0b688eb0489d6d4/smart-contract/config/CollectionConfig.ts#L7-L8
> 
> The env variables are now generic so there is no need to add new ones, you can simply use the default ones.

I still need to know if the project works as expected on OpenSea or if it requires some specific changes in order to support the Polygon chain correctly.

Thank you.

**Comment by Jonas-Lieske** [comment]
> I'm happy to hear this might be fixed. Infura (which is also used by MetaMask) had a lot of issue in the past days so I have seen many people complaining about failing transactions, wrong gas estimations, etc. I hope it was the culprit.

Yes, that could be the reason 🙂

>I still need to know if the project works as expected on OpenSea or if it requires some specific changes in order to support the Polygon chain correctly.

I have tested it on OpenSea and didn't encounter any error.

>Now I think we should take care of the optimizations suggested by OpenSea. I need to understand the purpose of each of them and I would like to limit the changes to what is absolutely required.

From what I can see the meta transactions would be a nice addition, not only for Polygon but also for Ethereum.
However, I haven't seen any comparable implementation on another marketplace, which might mean that this is only useful for OpenSea (or maybe I just missed an article 🤷‍♂️).
What do you think @liarco?

**Comment by liarco** [comment]
Thank you @Jonas-Lieske, I took a look at [the docs from OpenSea](https://docs.opensea.io/docs/polygon-basic-integration) and I found a reference to this at the bottom: https://docs.openzeppelin.com/learn/sending-gasless-transactions

But there you find a warning at the top, saying:
> This guide is now deprecated, as it uses GSNv1, which is no longer supported. Consider using [Defender](https://docs.openzeppelin.com/defender/) for [setting up your own meta-transaction relayers](https://blog.openzeppelin.com/gasless-metatransactions-with-openzeppelin-defender/) instead, or using GSNv2 from the [OpenGSN](https://opengsn.org/) team for a decentralized solution.

To me it's not clear if this method can still be considered a best-practice or if we should avoid it... I'm gonna do some more research! 😉

**Comment by nftkk** [comment]
> Here is my solution on how to implement Polygon support as discussed in #21.
> 
> **Requirements** The hardhat-etherscan package needs to be updated to version 3.0.0 since it offers a new feature to configure multiple API keys for scans at once. The doc entry is [HERE](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html#multiple-api-keys-and-alternative-block-explorers). I haven't noticed any problems with the update.
> 
> **Improvements that could be made** I do not have any experience with REACT so I didn't try to change anything on the code base. It still says ETH for the pricing and the polygon chain is not being recognized as a main chain. I also needed to use the gasMultiplier for polygon chain since there have been problems with the deployment and verification, because of a too low gas fee. AFAIK this is a problem with the calculation of gas fee by hardhat.
> 
> I tested it and it worked, however I only recently got into the field of smart contracts so I would appreciate any feedback!

Hello Jonas
thanks for your tread. i saw you are from germany as well :) maybe you help me to fix the issue with gas problems on the dapp? liarco guided me to this tread. 

here was my issue on closed tread: https://github.com/hashlips-lab/nft-erc721-collection/issues/96#issue-1163029074

**Comment by liarco** [comment]
@nftkk I'm sorry to say this but this is not actually what I meant. Here we are working on the implementation for the new feature, it's not a help-desk for personal support.

You are more than welcome to:
1. Download the code from the branch @Jonas-Lieske shared here (which features a testing implementation for Polygon)
2. Leave feedback here about what's working and what's not by providing with as much information as possible

If you can do this, then I will much appreciate it, but in the issue you linked above you are using a wrong version so we cannot help you with that.

**Comment by nftkk** [comment]
@liarco 
sorry i forget to share the information that i did transfer the lines from @Jonas-Lieske like he does already. so i meet the requirement for feedback? Sorry i really dont want to post useless stuff here.

**Comment by liarco** [comment]
> @liarco sorry i forget to share the information that i did transfer the lines from @Jonas-Lieske like he does already. so i meet the requirement for feedback? Sorry i really dont want to post useless stuff here.

Ok no problem, but please, since copying changes manually can lead to errors, I ask you to start from a clean copy of [the new code](https://github.com/Jonas-Lieske/nft-erc721-collection/archive/refs/heads/main.zip) and test it as a brand new project. You should then report what you are doing and what's happening.

Thank you for your time.

**Comment by granthughes1999** [comment]
Hello,

I used the link in your reply above that says "the new code" and downloaded that zip file (nft-erc721-collection-main). After successfully deploying on polygon, verifying the contract, yarn build the minting-dapp, deploying the minting-dapp on a static host and finally opening the whitelist, I am met with the an error on the minting-dapp page that says Error Unsupported Network. This occurs when i connect my metamask to polygon, which is where the contract was deployed and successfully verified on polyscan. The only step i can see causing this issue was when you add in your ContractAddress to CollectionConfig.js before verifying. I added the ContractAddress and set it as a string but i forgot to save the file before verifying the contract. do you think this miss-step could cause that issue? 

thanks for everything!!

**Comment by liarco** [comment]
Hi @granthughes1999, thank you for your detailed information. 🙏
I think you are missing the configuration explained here: https://github.com/hashlips-lab/nft-erc721-collection/pull/57#issuecomment-1060073605

You should tell the system that you are using polygon networks instead of the ethereum one. Let me know if it's clear enough! 😉

Thank you

**Comment by granthughes1999** [comment]
Hey @liarco ,

I went ahead and double-checked what I think is the configuration step, and my files all seem to be 100% up to date. The first step I took when running the new Zip files was to run npm install --save-dev @nomiclabs/hardhat-etherscan, which worked fine. I have now checked the 3 commits in this branch, and every line in my files matches the ones in the commits.
I also triple-checked the 3 lines you suggested adding to nft-erc721-collection/smart-contract/config/CollectionConfig.ts, in your above comment, those all match with my files as well.  I think I may be mistaken on what the configuration step is exactly, I'm sorry. Hopefully I am simply missing that step, I really appreciate you so much. 

Thanks!!

**Comment by liarco** [comment]
@granthughes1999 maybe I'm just misunderstanding what you say, but let's recap...

> I went ahead and double-checked what I think is the configuration step, and my files all seem to be 100% up to date. 

You are not supposed to do any manual check, you should just download the zip file and start from there (but here I think that's what you did, I point it out just in case...).

> The first step I took when running the new Zip files was to run npm install --save-dev @nomiclabs/hardhat-etherscan, which worked fine.

You shouldn't run any `npm install --save-dev @nomiclabs/hardhat-etherscan` (BTW this project doesn't use NPM, please use yarn). That zip file already contains the updated dependencies to make it compatible with Polygon, so you should just run `yarn` inside both `/minting-dapp` and `/smart-contract`, nothing else.

> I also triple-checked the 3 lines you suggested adding to nft-erc721-collection/smart-contract/config/CollectionConfig.ts, in your above comment, those all match with my files as well.

The lines I'm mentioning [here](https://github.com/hashlips-lab/nft-erc721-collection/pull/57#issuecomment-1060073605) should be changed according to the network that you want to use. If they match, then it's not a good thing because you have to import and reference the config for Polygon net instead of Ethereum (pleas confirm you also did that step as well).

Let me know if this is clear enough. 😉

**Comment by granthughes1999** [comment]
@liarco 

yes, I simply double checked the commits matched my files, which they did. I did not manually change any lines of code.

Yes, I use Yarn for everything else, I only used npm for this -> npm install --save-dev @nomiclabs/hardhat-etherscan,
I did this because in @Jonas-Lieske first post in this thread  "The doc entry is HERE", I thought we needed to update HardHat by following that Hardhat link, my mistake. 

so besides that, what is the configuration step I am missing? In the smart-contract terminal, I ran Yarn and installed all dependencies successfully, the same for the minting-dapp terminal. I also followed all steps very carefully. 

As for that final section of your comment, my files DO indeed match those 3 lines you posted (sorry I don't know how to link). Could you explain what those lines should be changed to? I'm sorry, I'm just not sure what they should be.

So much Appreciation,

**Comment by Jonas-Lieske** [comment]
> my files has both of those exact lines of code

The code is supposed to be changed like that:
`import { polygonTestnet, polygonMainnet} from '../lib/Networks';`

The network references should also be changed accordingly:
`testnet: polygonTestnet, mainnet: polygonMainnet,`

Let me know if this fixes your issue @granthughes1999!

**Comment by granthughes1999** [comment]
@liarco  @Jonas-Lieske 

Thank You, 
 
Both of your replies have solved all my issues. I have now successfully used nft-erc721-collection-main zip folder, to deploy a contract to polygon, verify it on polyscan, build and deploy the minting-dapp to a static host sever and successfully opened/closed the whitelist, presale, official sale. The minting worked on all stages, and the NFTs are visible on opensea!

I wanted to thank you both for the unbelievably quick responses and hard work you put into this entire repo. This project is one of a kind, thank you again!

**Comment by santosh-kumar-kaushal** [comment]
> @liarco @Jonas-Lieske
> 
> Thank You,
> 
> Both of your replies have solved all my issues. I have now successfully used nft-erc721-collection-main zip folder, to deploy a contract to polygon, verify it on polyscan, build and deploy the minting-dapp to a static host sever and successfully opened/closed the whitelist, presale, official sale. The minting worked on all stages, and the NFTs are visible on opensea!
> 
> I wanted to thank you both for the unbelievably quick responses and hard work you put into this entire repo. This project is one of a kind, thank you again!
> 
> I will update this post when I run the reveal! i don't assume any issues

@granthughes1999 Is this a branch which works fine ? I would like to test and see if this works. Thanks

**Comment by nftkk** [comment]
Hello guys
sorry for the late feedback. real life dont give time to test it again :) now i did use the code from @Jonas-Lieske and also change the additional lines for the polygon net.  after that i install the dependency. rename the contract to mine. fill my configurations to the new code. everthings works fine but to do the final test i have to open the white list. now i get a new error. but this has nothing to do with the code from jonas. i trie to open the whiteliste on my old backed up setup and also get timeout. is anything else on the provider for example?

$ hardhat run scripts/2_whitelist_open.ts --network mainnet
No need to generate any newer typings.
Enabling whitelist sale...
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\undici\lib\client.js:1005:28)
    at listOnTimeout (internal/timers.js:559:11)
    at processTimers (internal/timers.js:500:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment]
Hi @nftkk, thank you for your feedback. It seems like the CLI is failing connecting to the web3 provider (it should be Infura in your case since you are using `mainnet`). That should be the meaning of that timeout error.

Are you sure that the configuration is correct? (both Infura and `.env`)
I assume you also deployed the contract using the same `--network mainnet` flag so it worked at least once... that's what is really strange.

**Comment by nftkk** [comment]
i did double check everything right now. the .env is 1:1 same as my old one. if i do it severell times this comes:

 hardhat run scripts/2_whitelist_open.ts --network mainnet
No need to generate any newer typings.
Enabling whitelist sale...
ProviderError: already known
    at HttpProvider.request (C:\Users\kayhan\Documents\NFT KK Projekt\Programmieren\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:74:19)
    at LocalAccountsProvider.request (C:\Users\kayhan\Documents\NFT KK Projekt\Programmieren\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\hardhat\src\internal\core\providers\accounts.ts:182:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EthersProviderWrapper.send (C:\Users\kayhan\Documents\NFT KK Projekt\Programmieren\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

could be the reason that i run at first "compile" i dont know why i did this. i had in mind if you to open a new could and will use my old contract that i have to do this. was that wrong?

**Comment by liarco** [comment]
Ok @nftkk, now this is something different... 

First of all: there is no problem if you run `yarn compile`, it just cleans up the cache and compiles your contract again. Nothing bad should happen.

I tried looking for that `ProviderError: already known` error online and I found this: https://ethereum.stackexchange.com/a/91154

Now, from my understanding the "already known" error might be related to two transactions being run using the same nonce value. I guess this might happen because the Polygon network is much faster (?) but I don't understand why using async/await and `.wait()` is not avoiding this kind of issue...

Would you please try using the Truffle Dashboard tool? I ask this because having to interact manually might give enough time to process the nonce correctly, if that's the case then we might have to address this issue specifically.

Thank you very much.

**Comment by granthughes1999** [comment]
> i did double check everything right now. the .env is 1:1 same as my old one. if i do it severell times this comes:
> 
> hardhat run scripts/2_whitelist_open.ts --network mainnet No need to generate any newer typings. Enabling whitelist sale... ProviderError: already known at HttpProvider.request (\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:74:19) at LocalAccountsProvider.request (\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\hardhat\src\internal\core\providers\accounts.ts:182:36) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async EthersProviderWrapper.send (\hashlips\nft-erc721-collection-poly\smart-contract\node_modules@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> could be the reason that i run at first "compile" i dont know why i did this. i had in mind if you to open a new could and will use my old contract that i have to do this. was that wrong?

I have run into this error. My best solution is to save all your files and restart your computer. If this file automatically opens back up in Vscode when you restart your computer, it is best to close it out and open a new Vscode window. From there I run yarn dashboard and reconnect my metamask to the dashboard. I then can run all yarn commands like normal. I typically encounter this error when I close my laptop for the night and return the next day.

Hope this helps! @nftkk

**Comment by nftkk** [comment]
@[granthughes1999](https://github.com/granthughes1999)
thanks. i try this out right now. it does not help :(

now i install the truffle dashboard like this tread: https://github.com/hashlips-lab/nft-erc721-collection/pull/49
connect it to my wallet, right network.
image

in my other terminal with the contract i connect to truffle yarn --network truffle it loads me the list of the commands. tipe whitelist-open. but get this error:
image

image

**Comment by liarco** [comment]
@nftkk I think you are doing something wrong here...

`yarn --network truffle` is not a valid command (it doesn't exist, where did you see it?), so I don't know what you are trying to do by running it. You should append `--network truffle` to each command in order to use Truffle Dashboard instead of the `.env` file (e.g. `yarn whitelist-open --network truffle`).

The latest error means that there is no contract deployed to the address set in your configuration. So either you still didn't deploy the contract, or maybe you deployed it to one network and now your Truffle Dashboard is connected to another one.

**Comment by nftkk** [comment]
Hi
puh i am not sure really. i thought it was correct because i dont get any error.

tried your suggestion right now. came out following error in metamask this time:

Transaction decoding is not available for chainId 137

PS \hashlips\nft-erc721-collection-poly\smart-contract> yarn whitelist-open --network truffle
yarn run v1.22.15
warning package.json: No license field
$ hardhat run scripts/2_whitelist_open.ts --network truffle
No need to generate any newer typings.
Enabling whitelist sale...
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (\hashlips\nft-erc721-collection-poly\smart-contract\node_modules\undici\lib\client.js:1005:28)
    at listOnTimeout (internal/timers.js:559:11)
    at processTimers (internal/timers.js:500:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment]
Thank you @nftkk, but please use codeblocks (3 backticks `` ``` `` before and after your pasted code/error) so we can read it properly, I edited your previous message so you can take it as a reference.

The default configuration for the Truffle Dashboard has a timeout of 20 seconds, if you don't process the transaction quickly you are gonna end up with the timeout error. I'm gonna set an higher value in future versions (check #113 to test this change in your project if you wish, it's just one line of code).

I'm still confused by the `Transaction decoding is not available for chainId 137` error from MetaMask. I found [this thread](https://www.reddit.com/r/Metamask/comments/rtkx3l/failed_transactions_transaction_decoding_is_not/) where people say it might be related to errors with gas fees estimation. If that problem persists you might try fixing it by setting the `gasEstimation` property of your network to `1.1` (as suggested by @Jonas-Lieske). You can do it the same way as the timeout value.
Gas estimation is handled by the provider so if MetaMask or Infura struggle doing their calculations there isn't much that we can do about it, I don't like the idea of setting a gas multiplier by default, but we might introduce a way to quickly set it for all of the networks.

**Comment by nftkk** [comment]
okay @liarco 
i didnt find a line in the hardhat.config to increase the gas multiplier. after timeout change:

```$ hardhat run scripts/2_whitelist_open.ts --network truffle
```No need to generate any newer typings.
```Enabling whitelist sale...
```ProviderError: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":```{"code":-32603,"message":"Internal error"}}}'
```    at HttpProvider.request (\hashlips\nft-erc721-collection-```poly\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:74:19)
```    at GanacheGasMultiplierProvider.request (C:\Users\kayhan\Documents\NFT KK Projekt\Programmieren\hashlips\nft-```erc721-collection-poly\smart-contract\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:312:34)
```    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```error Command failed with exit code 1.
```info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```PS \hashlips\nft-erc721-collection-poly\smart-contract>

**Comment by liarco** [comment]
@nftkk we didn't set a custom gas multiplier in our standard config, so you won't find it there.

You can add it like this:
```
  networks: {
    truffle: {
      url: 'http://localhost:24012/rpc',
      timeout: 60000,
      gasMultiplier: 1.1,
    },
  },
```

This is for Truffle Dashboard, the other networks have their own configuration around lines `120-135`, but you can skip them if not using them.

I really appreciate you taking this time in order to test this, this weekend I'm also gonna take some time to test this PR extensively in order to understand how it performs under various conditions.

**Comment by Juan34-crypto** [comment]
Hi !! I’m one step to drop my collection on the polygon blockchain but I’m facing this errors

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Juan34-crypto** [comment]
I have a big problem when trying to deploy the smart contract with ( yarn deploy —network mainnet)
07B8A6BD-4219-42F3-B393-2FEDFFA4A692

**Comment by Juan34-crypto** [comment]
Please helppp me @Jonas-Lieske @liarco @nftkk im one step to drop my collection and I don’t know what to do 😩

**Comment by liarco** [comment]
@Juan34-crypto please calm down. This is not something you should take this way. It took me months (after 23 years studying/working as a developer) in order to get here, you should take your time nobody can speed it up for you here. It's all up to you.

Your error is a connection error, you should check your configuration, maybe start over and follow every step really carefully.

This is also an unstable version of this software, you are not supposed to launch a real project with this, so I don't see any reason to rush. We need to get this done right, not fast.
If you need this to be "fast", then there are plenty of developers out there that can be hired for this. 😉

**Comment by nftkk** [comment]
@liarco 
thanks for your help. i try my best to give you and the community best feedback as its possible for me.

not i have a funny think. i start my terminal an run whiteliste open by the .env with private keys. today it works. i did nothing change. maybe yesterday the blockhain was busy and the gas fees higher. it seems that infura cant handle this. it is the clean code of @Jonas-Lieske

after that i rund the dev-server and connect a wallet wich was on white list and try to mint. i get the same error as before. so there was no faults on my code before.

image

At this point it must have something to do with DAPP and the configuration. I wonder why a gas fee is pre-calculated at this point, but from here on out it has to run normally via meta mask. Or have I thought incorrectly about that?

**Comment by nftkk** [comment]
thanks for support! we are working on a different layout from the minting dapp. i will share if it is done next week.

just bought an ape from you to support you guys!!!!

image

**Comment by liarco** [comment]
> update: i was sooo stupid. this error comes if you have not enough matic on the wallet.... sorry guys. everything works perfect!!!!

You were not stupid at all. We try to make this stuff accessible to a lot of people, but it's not easy to understand how everything works and all the things that can go wrong. It takes time and a lot of trial and error. Take your time, you will improve with time, like all of us. 

> just the one question is very interesting. how will opensea handle the floorprice if we sell on matic wich is not supported on opensea?

You should check this out on the [test version of OpenSea](https://testnets.opensea.io).

**Comment by nftkk** [comment]
I have now run a full test on the Mumbai Network.

There are 2 important points that are missing.

1. rarity of properties in %. It says "new traid" instead of the %
2. no floor price

i think this is very important for an collection. of course the target is to sell out on minting dapp but is is very important to show up an floor price for it. how was that on eth chain? is there a floor price?

how can i add the % rarrity of the properties?

**Comment by liarco** [comment]
@nftkk would you mind sharing the links so we can check it out? The first point should have nothing to do with this project, it might be just a "cache" issue (many ethereum collections on mainnet show the same thing at the beginning). I have no clue about floor price and volume.

**Comment by nftkk** [comment]
I did some research. the floor price and the trading volume only get tracked if you list directly on opensea, without own smart contract. i think i will run it on this way.

there are 2 ways: 

1. to do it with an smart contract
2. directly on opensea like this guy https://www.youtube.com/watch?v=OfqmR2lvU8E

i want to got the 1st way, this was more professional for me.

how can i send an selected nft to the owner? i just know how to mint to owner on polycan but dont now how i can choose the number of the nft there.

**Comment by goshaminsk** [comment]
Thanks for Polygon support!

I have an issue to verify a contract on the Mumbai Network

getting an error: Error in plugin @nomiclabs/hardhat-etherscan: Missing or invalid ApiKey

In .env file I added the API Key from polygon.io 

Thank you

**Comment by liarco** [comment]
@nftkk you can specify the amount of NFTs to mint for an address, not the IDs.

@goshaminsk You are supposed to use the API key from polygonscan.

**Comment by ecerroni** [comment]
@goshaminsk did you also apply the changes mentioned here?
https://github.com/hashlips-lab/nft-erc721-collection/pull/57#issuecomment-1063332749

**Comment by ecerroni** [comment]
> how can i send an selected nft to the owner? i just know how to mint to owner on polycan but dont now how i can choose the number of the nft there.

When you use the mint function you just pass the amount of token you want to mint. This is true also if the minter is the owner.

If you want to mint specific NFTs for the owner you should do it on contract deploy. Let's say you want to mint the first 100 tokens in the contract. You should add a mint function like the following:

**Comment by goshaminsk** [comment]
> @goshaminsk You are supposed to use the API key from polygonscan.

Successfully verified contract on Etherscan

Thank you for you help!

**Comment by Berenike29** [comment]
Hi @liarco and @Jonas-Lieske Just wanted to let you know that I was able to deploy my contract successfully to the Polygon Mainnet using the updated contract! Thank you so, so much for making this possible!!

**Comment by ecerroni** [comment]
I used this repo to deploy multiple versions of my smart contract on the Mumbai Testnet. I also imported them into Opensea with no issues. First time it took something like half an hour, but subsequent contracts deployed with the same owner address got imported automatically.

Once ready I deployed it to the Polygon Mainet following the same procedure. Everything went fine and the smart contract is on the blockchain: https://polygonscan.com/address/0xD15c3c9306ccD6D7c575a730A8cCb29bF98dB755.

However, here there is the issue. Opensea keeps giving me the following error when I try to import it:
`We couldn't find this contract. Please ensure that this is a valid ERC721 or ERC1155 contract deployed on Polygon and that you have already minted items on the contract.`

It's been more than 36 hours so far. Any idea on what I might have done wrong?

The only thing that comes to my mind is that I did `yarn rename-contract UBW` to rename it from `TestBW`. So I did it the first time for Testnet, and then again for Mainet. I've inspected the function and it does not seem to me that it could cause problems renaming it twice 🤔 

Hopefully some of you can give me an insight.

**Comment by liarco** [comment]
Hi @ecerroni, I know that OpenSea doesn't allow you to import collections where no token has been minted yet. Can this be the issue in your case?

**Comment by ecerroni** [comment]
@liarco I've minted them all after contract deploy. Now totalSupply is equal to maxSupply. I guess that should be it 🤔 

Here there is the contract https://polygonscan.com/address/0xD15c3c9306ccD6D7c575a730A8cCb29bF98dB755

I still hope it's all been about bad timing. Maybe I had no luck while deploying following Polygon’s network outage last week. Indeed they announced yesterday that they will implement a hard fork on Heimdall that I hope will somehow make my contract reemerge in front of OpenSea if that was actually the issue.

If that will not happen in the next few days then I have no idea what happened.

@Berenike29 @goshaminsk were you able to deploy on Polygon Mainet and import the contract on OpenSea or was it just on Testnets?

**Comment by Berenike29** [comment]
Hi @ecerroni yes I was able to deploy on the Polygon mainnet!

**Comment by ecerroni** [comment]
> Hi @ecerroni yes I was able to deploy on the Polygon mainnet!

Thanks for chiming in. Were you also able to import the same contract on OpenSea and start selling items?

**Comment by liarco** [comment]
@ecerroni are you sure that your tokens are not under the "hidden" tab on Opensea? Is this your profile? https://opensea.io/waucollections

Because, since Polygon tokens are really cheap, OpenSea sets them as hidden by default in order to avoid showing promotional tokens on profile pages.

-----

Anyway I run some tests together with other devs and this PR seems finally ready to be merged. This feature will be included in the next release asap, I want to thank everyone for contributing (especially @Jonas-Lieske for the initial proposal).

**Comment by Prickheads** [comment]
Hi, thanks for all this work and help regarding deploying to Polygon.
I was able to follow along nicely and have managed to deploy a contract to Mumbai without issue.
I have followed all the steps with regards to the following links in this post:
steps
However, getting to the minting dapp, I keep getting the following error saying unsupported network while metamask is connect to Mumbai which the contract verified to with no issues.
Any ideas on why can't get the dapp to connect to the poly networks (same Unsupported Network if switch to Poly mainnet)?
dapp
Thanks again for the help and posting all this info and work!

**Comment by Prickheads** [comment]
Hi again, I have seemed to figure out my previous post and somehow had missed a comment from you regarding a couple changes in the the CollectionConfig.ts that you mentioned here:
https://github.com/hashlips-lab/nft-erc721-collection/pull/57#issuecomment-1060073605

I made these changes, changing the ethereum labels to polygon on these lines, and the Dapp seems to be working fine now!

Thanks once again for these posts and the help!
I'll be testing things out now on Mumbai thanks to you^^

**Comment by Dulzz69** [comment]
Hello guys, first of all thank you very much for your works. I learnt so many things from you.
I want to confirm a thing. Can I create a DAPP from this for a already deployed smart contract that using remix? (I have the abi code). In other words, can I create a DAPP from this without this smart contract?

**Pull request merged**
